---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/concept
  label: Concept
  create: all
  match: "**/*"
- type: directory
  path: content/faq
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: content/collections
  label: Collections
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/how
  label: How
  create: all
  match: "**/*"
- type: directory
  path: content/jobs
  label: Jobs
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/steps
  label: Steps
  create: all
  match: "**/*"
  templates:
  - steps
- type: directory
  path: content/stories
  label: Stories
  create: all
  match: "**/*"
- type: directory
  path: content/partners
  label: Partners
  create: all
  match: "**/*"
  templates:
  - partners
- type: directory
  path: content/form
  label: Form
  create: all
  match: "**/*"
- type: directory
  path: content/emmaus
  label: Emmaus
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: https://res.cloudinary.com/hemmlis
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.42.1
