# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hemmlis"
license = "All Rights Reserved"
description = "A theme for the Hemmlis homepage"
homepage = "http://www.hemmlis.se/"
tags = ["hemmlis", "furniture"]
features = ["custom everything"]
min_version = 0.18

[author]
  name = "Thobias Bergström"
  homepage = "https://github.com/thobias"
